### ISSUE TITLE
implement DeletebyQuery

### ISSUE THREAD

**Issue by enesyalinkaya** [Trendyol/go-dcp-elasticsearch#72]
When deleting documents that are indexed using routing, it is necessary to use routing for the deletion as well. Since the DCP deletion event only provides the document key, workaround solutions are needed to find the routing value.

 We can also perform the deletion using 'Delete by query'. Can we implement 'Delete by query'?"

**Comment by erayarslan** [comment]
`Delete by query` is mostly a search operation. We can give freedom, but this brings problems such as conflict/refresh to handle. Because of this problems, personally i did not want it on connector but if it is really necessary, i will follow.

I want to ask, why we cannot regenerate this routing key from event? for your routing problem.

**Comment by erayarslan** [comment]
We discuss internally with @enesyalinkaya and decited to forward with fetch and delete solution.
Because of that we give freedom to access elastic client from mapper to user with [this](https://github.com/Trendyol/go-dcp-elasticsearch/commit/72341cd489a0942eec29f38e1ceed3e2adba8e3c) implementation.
